#!/bin/bash

if [[ $LD_LIBRARY_PATH =~ "qcustomplot" ]]; then
	echo -e "qcustomplot in library path\n"
	echo $LD_LIBRARY_PATH
else
	p=$(pwd)
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$p"
fi

if [ -f 'exe' ]; then
	rm exe
fi

make

if [ -f 'exe' ]; then
	time ./exe "$@"
fi
