#!/bin/bash

if [[ $LD_LIBRARY_PATH =~ "qcustomplot" ]]; then
	echo -e "qcustomplot in library path\n"
else
	echo -e "adding qcustomplot to library path\n"
	LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/../qcustomplot
fi

if [ -f 'exe' ]; then
	rm exe
fi

make

if [ -f 'exe' ]; then
	time ./exe "$@"
fi
